const DENORMALIZED_DATA_HEADERS = {
    GENDER: "char_gender",
    NAME: "char_name",
    CREDIT_LINE_POS: "credits_position",
    TITLE: "movie_title",
    GENRES: "genres",
    YEAR: "year",
    IMDB_RATING: "IMDB_rating",
};

const PLACEHOLDER_TO_DATA_HEADER_MAP = {
    "Name": DENORMALIZED_DATA_HEADERS.NAME,
    "Credit Line Position": DENORMALIZED_DATA_HEADERS.CREDIT_LINE_POS,
    "Movie Title": DENORMALIZED_DATA_HEADERS.TITLE,
    "Genre": DENORMALIZED_DATA_HEADERS.GENRES,
};

const SLIDER_HEADERS = [
    DENORMALIZED_DATA_HEADERS.CREDIT_LINE_POS,
    DENORMALIZED_DATA_HEADERS.YEAR,
    DENORMALIZED_DATA_HEADERS.IMDB_RATING,
];

const ALL_VALUES = "SELECT_ALL";

const INITIAL_FILTER_MODEL = {
    [DENORMALIZED_DATA_HEADERS.GENDER]: ["f", "m", "?"],
    [DENORMALIZED_DATA_HEADERS.NAME]: ALL_VALUES,
    [DENORMALIZED_DATA_HEADERS.CREDIT_LINE_POS]: ALL_VALUES,
    [DENORMALIZED_DATA_HEADERS.TITLE]: ALL_VALUES,
    [DENORMALIZED_DATA_HEADERS.GENRES]: ALL_VALUES,
    [DENORMALIZED_DATA_HEADERS.YEAR]: ALL_VALUES,
    [DENORMALIZED_DATA_HEADERS.IMDB_RATING]: ALL_VALUES,
};

export {
    DENORMALIZED_DATA_HEADERS,
    PLACEHOLDER_TO_DATA_HEADER_MAP,
    SLIDER_HEADERS,
    ALL_VALUES,
    INITIAL_FILTER_MODEL,
}